### ISSUE TITLE
Cloning the wiki fails.

### ISSUE THREAD

**Issue by kamal2311** [jboursiquot/serverless-go-orchestration-on-aws-course#1]
Trying to clone the wiki with 
`git clone https://github.com/jboursiquot/serverless-go-orchestration-on-aws-course.wiki.git`

causes clone to succeed but the checkout to fail.

**Comment by jboursiquot** [comment]
Hmm...I can't reproduce this issue. Hopefully accessing the content directly on GitHub still works for you.
